Streamline tests for sorts
eloreprojects/programjs pull request #14
Opened 2017-07-21 17:07 UTC by n3a9

2017-07-21 23:38 UTC, kirubarajan requested changes
Can we get rid of the hardcoded array sizes?

2017-07-22 00:24 UTC, n3a9 commented
Good call, I'll do that.

2017-07-22 01:54 UTC, n3a9 commented
Randomized sizing in both sort tests and stack tests, and updated console logging.

2017-07-22 03:32 UTC, kirubarajan approved these changes
Looks good

2017-07-22 03:33 UTC, merged